# Name your workflow
name: demo-deployment-workflow

# Specify when this workflow should trigger
on:
  push:
    # This will only run when we make pushes on the main branch and development branch
    branches: ['main', 'development']

  # This lets us run the workflow manually through the GitHub actions page
  workflow_dispatch:

# Specify the jobs in this workflow. Jobs we want to run
# "Build and test"
# "Deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'create script'
        run: echo 'echo "hello horizon team!"' > helloworld.sh
      - name: turn script into executable
        run: chmod +x helloworld.sh
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world
          path: helloworld.sh

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world
          path: .
      - name: upload script to horizon devops server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HORIZON_SSH_HOST }}
          username: ${{ secrets.HORIZON_SSH_USER }}
          key: ${{ secrets.HORIZON_SSH_KEY }}
          source: helloworld.sh
          target: /home/horizon/
