name: demo-deployment-workflow

on:
  push:
    branches: ['main', 'development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'create script'
        run: echo 'echo "hello horizon team!"' > hellohorizon.sh
      - name: turn script into executable
        run: chmod +x hellohorizon.sh
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-horizon
          path: hellohorizon.sh

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-horizon
          path: .
      - name: copy script with scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USER }}
          password: ${{ secrets.DEMO_PASS }}
          source: 'helloworld.sh'
          target: '/root/horizon'
