name: demo-deployment-workflow

on:
  push:
    branches: ['main', 'development']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'build step'
        run: |
          echo "building horizon demo"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: copy script via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USER }}
          password: ${{ secrets.DEMO_PASS }}
          source: 'helloworld.sh'
          target: '/root/horizon'
