# You can control deployments with github actions by
# triggering workflows after events
# configure environments to set rules before running a job
# use concurrency to control number of deployments running at a time

name: cd-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

# ENVIRONMENTS - used to describe a general deployment target like `production`, `staging` or `development`
# environment is displayed on main page of repo if GHA deploys to it
# can use environments to require approval for a job to proceed & other governance controls

# CONCURRENCY - ensures a single job or workflow using the same concurrency group will run at a time
# use concurrency to make sure an environment only has one deployment in progress and one in pending at a time
# not connected to environment names

jobs:
  deployment:
    runs-on: ubuntu-latest
    # specifies which environment to use
    environment: production
    # specifies concurrency group so there will only be one running and one pending job/workflow in this group
    concurrency: production
    steps:
      - name: deploy
        run: echo "deploying application"
