# Name your workflow
name: demo-deployment-workflow

# Specify when this workflow should trigger
on:
  push:
    # This will only run when we make pushes on the main branch and development branch
    branches: ['main', 'development']

  # This lets us run the workflow manually through the GitHub actions page
  workflow_dispatch:

# Specify the jobs in this workflow. Jobs we want to run
# "Build and test"
# "Deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: install dependencies
        run: npm ci
        working-directory: nest-api

      - name: run test suite
        run: npm run test
        working-directory: nest-api

      - name: build distribution folder
        run: npm run build
        working-directory: nest-api

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nest-api-dist
          path: nest-api/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: nest-api-dist
          path: ./dist/

      - name: upload script to horizon devops server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HORIZON_SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist'
          target: /root/horizon/
