# A runner is a server that runs your workflow when they are triggered

# Name your workflow
name: download-artifact-workflow

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file # specify assigned artifact name to download
